### ISSUE TITLE
It does not work now after the auto update

### ISSUE THREAD

**Issue by CicoZhang** [orschiro/switch-recent-tabs-chrome-extension#37] opened 2018-05-07 15:31 UTC
It does not work any longer after today's automatic update. Please fix it! Thanks in advance.

**Comment by orschiro** [comment] 2018-05-07 17:05
@CicoZhang please help us debugging:

https://github.com/orschiro/switch-recent-tabs-chrome-extension/wiki/FAQ#help-us-debugging

**Comment by orschiro** [comment] 2018-05-07 17:06
Duplicate of #17

**Closed by orschiro** 2018-05-07 17:05 UTC
