### ISSUE TITLE
Closing a tab forgets the previous tab

### ISSUE THREAD

**Issue by abstrakt** [orschiro/switch-recent-tabs-chrome-extension#18] opened 2018-03-05 10:51 UTC
Ever since the last update, whenever you close a tab, toggling this extension no longer works until you go to a new tab.

Before, it retained your previous tab even if you had closed a tab.

**Comment by orschiro** [comment] 2018-03-05 11:39
@abstrakt I removed this functionality to keep this extension more clean and focused to its original purpose. 

You can still get an [older version](https://github.com/orschiro/tsrlt-chrome-extension/releases) that still has this feature or install an extension that provides this feature, like [Last Tab](https://chrome.google.com/webstore/detail/last-tab/ahjejhiehlhdhcgpifiappdhdjhbhcpf).

**Comment by orschiro** [comment] 2018-03-08 09:15
Duplicate of https://github.com/orschiro/switch-recent-tabs-chrome-extension/issues/20

**Comment by frankyjuang** [comment] 2018-03-09 05:36
@abstrakt can you confirm that this is solved after updating to ver.9

**Comment by orschiro** [comment] 2018-03-09 10:04
@abstrakt @frankyjuang for me it's working and remembering the last tab before the two recent tabs, for what it's worth.

**Comment by abstrakt** [comment] 2018-03-09 10:15
@frankyjuang I can confirm this is working now. Thanks for this! It's a quality of life enhancement.

**Comment by orschiro** [comment] 2018-03-09 10:17
@abstrakt thanks for confirming and thanks to @frankyjuang for his great contribution on this! :-)

**Closed by orschiro** 2018-03-09 10:17 UTC
Labels: bug, duplicate, help-wanted
